######################################################################
# Automatically generated by qmake (2.01a) ?? 14. ??? 13:38:42 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . debug
INCLUDEPATH += .
INCLUDEPATH += $(SANDBOX)\boost_1.39.0

# Input
HEADERS += imath.h ipoint.h ipoint_alg.h iview.h rect.h vec.h
SOURCES += imath.cpp ipoint.cpp ipoint_alg.cpp iview.cpp main.cpp
RESOURCES += ipoint.qrc
